version: 2.0.3-alpha{build}
branches:
  only:
  - master
  - develop
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
install:
- choco install msbuild.communitytasks -y
build:
  project: build.msbuild
  verbosity: normal
artifacts:
- path: build/package/**/*.nupkg
  name: Package
deploy:
- provider: NuGet
  api_key:
    secure: fnfp0KvYrSJ4VETGtf4WyajYJnyKVIQsde+8uzQ42ERjcSPpCfX9fYlqrK3kHEp5
  artifact: '*.nupkg'
- provider: GitHub
  tag: v{appveyor_build_version}
  auth_token:
    secure: UfVipK2YzugPd54B3ls2zFwGuZVeMTH9cXwP22V9RVO/AACEjvROyFGspb1/ljwm
  artifact: '*.zip'
  on:
    branch: master